### ISSUE TITLE
Questions about DeepUrbanEvent

### ISSUE THREAD

**Issue by zijiancao** [deepkashiwa/DeepUrbanEvent#3]
Hello, Dr Wang, there are two layers of encoder and two layers of decoder used in the network, but I am not quite sure about the input of the second layer of encoder and the output of the decoder.How the Crowd density and Crowd flow are input to the convlstm encoder on the second floor and how the output from the encoder on the second floor convlstm is divided into Crowd density and Crowd flow.

**Comment by underdoc-wang** [comment]
Hi there. The input to the second layer of encoder is the concatenation of the hidden states of crowd density and flow through their first layers respectively, so that crowd density and flow are mixed in the hidden state of the second layer (not divided here). Hope it answers your question.

**Comment by zijiancao** [comment]
Thank you very much, Dr. Wang! 
Finally, I would like to ask you a question. Graph neural network is also very popular in urban traffic prediction. Have you considered using graph to represent area instead of regular grid. In other words, why not choose graph to represent it and use regular grid? I want to hear your opinion.
| |
曹子健
|
|
***@***.***
|
签名由网易邮箱大师定制
On 5/26/2021 ***@***.***> wrote：

Hi there. The input to the second layer of encoder is the concatenation of the hidden states of crowd density and flow through their first layers respectively, so that crowd density and flow are mixed in the hidden state of the second layer (not divided here). Hope it answers your question.

**Comment by underdoc-wang** [comment]
I think it depends on the entity you're abstracting. Traffic network is naturally represented by a graph - it'll be awkward to use grid. In contrast, when discretizing a 2D space, we have the choice to do it in either way. Although in an urban setting, a graph representation makes more sense since the translation invariance does not hold. But anyway, if you simply apply a CNN and localized GCN (with adjacency matrix input), you are expected to get a similar result.
